apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
  - name: curl
    image: docker.io/curlimages/curl
    runAsUser: '1000'
    command:
    - cat
    tty: true
  volumes:
  - name: docker-config
    secret:
      # Add secret to cluster:
      # kubectl create secret docker-registry docker-credentials \
      #   --docker-username=[userid] \
      #   --docker-password=[Docker Hub access token] \
      #   --docker-email=[user email address] \
      #   --namespace [jenkins namespace]
      secretName: docker-credentials
      items:
      - key: .dockerconfigjson
        path: config.json